spring:
  datasource:
    url : jdbc:mysql://localhost:3306/springboot?characterEncoding=UTF-8
    username : root
    password : 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  application:
    name: sayHelloClient
securityconfig:
  loginSuccessUrl: /
  permitAll: /login,/user/login.do
  deniedPage: /user/deny.do
  userRoles: /*/*Add.do = admin
server:
  port: 8888
  sessionTimeout: 15
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer2:2222/eureka/,http://peer1:1111/eureka/
sayHelloServer:
  ribbon:
    NFLoadBanlancerRuleClassName: com.netflix.loadbalancer.RandomRule

